[2024-12-05T14:38:59.011+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T14:38:59.020+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_warehouse_etl_standard.load_fact_table manual__2024-12-05T13:33:29.205192+00:00 [queued]>
[2024-12-05T14:38:59.023+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_warehouse_etl_standard.load_fact_table manual__2024-12-05T13:33:29.205192+00:00 [queued]>
[2024-12-05T14:38:59.023+0100] {taskinstance.py:2866} INFO - Starting attempt 1 of 3
[2024-12-05T14:38:59.028+0100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_fact_table> on 2024-12-05 13:33:29.205192+00:00
[2024-12-05T14:38:59.032+0100] {standard_task_runner.py:72} INFO - Started process 54655 to run task
[2024-12-05T14:38:59.036+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_warehouse_etl_standard', 'load_fact_table', 'manual__2024-12-05T13:33:29.205192+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/data_warehouse_etl_dag.py', '--cfg-path', '/var/folders/4k/bhptqqm131v6f034phck6fc80000gn/T/tmpe6qqh37d']
[2024-12-05T14:38:59.038+0100] {standard_task_runner.py:105} INFO - Job 76: Subtask load_fact_table
[2024-12-05T14:38:59.056+0100] {task_command.py:467} INFO - Running <TaskInstance: data_warehouse_etl_standard.load_fact_table manual__2024-12-05T13:33:29.205192+00:00 [running]> on host sijibomis-mbp
[2024-12-05T14:38:59.075+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering' AIRFLOW_CTX_DAG_ID='data_warehouse_etl_standard' AIRFLOW_CTX_TASK_ID='load_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T13:33:29.205192+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T13:33:29.205192+00:00'
[2024-12-05T14:38:59.075+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T14:38:59.143+0100] {load.py:128} ERROR - Fact table loading error: (builtins.TypeError) Not a boolean value: 'No'
[SQL: INSERT INTO fact_task_tracking (date, hours, billable, task_description) VALUES (?, ?, ?, ?)]
[parameters: [{'hours': 2.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-10 00:00:00'), 'billable': 'No'}, {'hours': 0.5, 'task_description': 'Un ... (50676 characters truncated) ... -07-23 00:00:00'), 'billable': 'Yes'}, {'hours': 0.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-24 00:00:00'), 'billable': 'Yes'}]]
[2024-12-05T14:38:59.143+0100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
            ^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 2000, in process
    value = _strict_as_bool(value)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1975, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % (value,))
TypeError: Not a boolean value: 'No'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/src/data_pipeline/load.py", line 121, in load_fact_table
    session.bulk_save_objects(fact_entities)
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3705, in bulk_save_objects
    self._bulk_save_mappings(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3912, in _bulk_save_mappings
    with util.safe_reraise():
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3901, in _bulk_save_mappings
    persistence._bulk_insert(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 107, in _bulk_insert
    _emit_insert_statements(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
            ^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 2000, in process
    value = _strict_as_bool(value)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1975, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % (value,))
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: 'No'
[SQL: INSERT INTO fact_task_tracking (date, hours, billable, task_description) VALUES (?, ?, ?, ?)]
[parameters: [{'hours': 2.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-10 00:00:00'), 'billable': 'No'}, {'hours': 0.5, 'task_description': 'Un ... (50676 characters truncated) ... -07-23 00:00:00'), 'billable': 'Yes'}, {'hours': 0.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-24 00:00:00'), 'billable': 'Yes'}]]
[2024-12-05T14:38:59.156+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_warehouse_etl_standard, task_id=load_fact_table, run_id=manual__2024-12-05T13:33:29.205192+00:00, execution_date=20241205T133329, start_date=20241205T133859, end_date=20241205T133859
[2024-12-05T14:38:59.161+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T14:38:59.161+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 76 for task load_fact_table ((builtins.TypeError) Not a boolean value: 'No'
[SQL: INSERT INTO fact_task_tracking (date, hours, billable, task_description) VALUES (?, ?, ?, ?)]
[parameters: [{'hours': 2.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-10 00:00:00'), 'billable': 'No'}, {'hours': 0.5, 'task_description': 'Un ... (50676 characters truncated) ... -07-23 00:00:00'), 'billable': 'Yes'}, {'hours': 0.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-24 00:00:00'), 'billable': 'Yes'}]]; 54655)
Traceback (most recent call last):
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
            ^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 2000, in process
    value = _strict_as_bool(value)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1975, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % (value,))
TypeError: Not a boolean value: 'No'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/src/data_pipeline/load.py", line 121, in load_fact_table
    session.bulk_save_objects(fact_entities)
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3705, in bulk_save_objects
    self._bulk_save_mappings(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3912, in _bulk_save_mappings
    with util.safe_reraise():
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3901, in _bulk_save_mappings
    persistence._bulk_insert(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 107, in _bulk_insert
    _emit_insert_statements(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1816, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1810, in _execute_context
    context = constructor(
              ^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1077, in _init_compiled
    param = [
            ^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 1078, in <listcomp>
    processors[key](compiled_params[key])
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 2000, in process
    value = _strict_as_bool(value)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/sqlalchemy/sql/sqltypes.py", line 1975, in _strict_as_bool
    raise TypeError("Not a boolean value: %r" % (value,))
sqlalchemy.exc.StatementError: (builtins.TypeError) Not a boolean value: 'No'
[SQL: INSERT INTO fact_task_tracking (date, hours, billable, task_description) VALUES (?, ?, ?, ?)]
[parameters: [{'hours': 2.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-10 00:00:00'), 'billable': 'No'}, {'hours': 0.5, 'task_description': 'Un ... (50676 characters truncated) ... -07-23 00:00:00'), 'billable': 'Yes'}, {'hours': 0.0, 'task_description': 'Unspecified', 'date': Timestamp('2023-07-24 00:00:00'), 'billable': 'Yes'}]]
[2024-12-05T14:38:59.185+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-05T14:38:59.191+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T14:38:59.191+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
