[2024-12-04T15:47:52.678+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-04T15:47:52.683+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_warehouse_etl.load_dimensions manual__2024-12-04T14:42:16.988033+00:00 [queued]>
[2024-12-04T15:47:52.686+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_warehouse_etl.load_dimensions manual__2024-12-04T14:42:16.988033+00:00 [queued]>
[2024-12-04T15:47:52.686+0100] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-04T15:47:52.696+0100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_dimensions> on 2024-12-04 14:42:16.988033+00:00
[2024-12-04T15:47:52.699+0100] {standard_task_runner.py:72} INFO - Started process 46326 to run task
[2024-12-04T15:47:52.703+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_warehouse_etl', 'load_dimensions', 'manual__2024-12-04T14:42:16.988033+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dim_process.py', '--cfg-path', '/var/folders/4k/bhptqqm131v6f034phck6fc80000gn/T/tmpo8co3t16']
[2024-12-04T15:47:52.706+0100] {standard_task_runner.py:105} INFO - Job 23: Subtask load_dimensions
[2024-12-04T15:47:52.724+0100] {task_command.py:467} INFO - Running <TaskInstance: data_warehouse_etl.load_dimensions manual__2024-12-04T14:42:16.988033+00:00 [running]> on host sijibomis-MacBook-Pro.local
[2024-12-04T15:47:52.745+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering' AIRFLOW_CTX_DAG_ID='data_warehouse_etl' AIRFLOW_CTX_TASK_ID='load_dimensions' AIRFLOW_CTX_EXECUTION_DATE='2024-12-04T14:42:16.988033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-04T14:42:16.988033+00:00'
[2024-12-04T15:47:52.746+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-04T15:47:52.803+0100] {logging_mixin.py:190} WARNING - /Users/sijibomijoshua/airflow/dags/dim_process.py:86 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-12-04T15:47:52.804+0100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/dags/dim_process.py", line 86, in load_dimensions
    projects.to_sql('dim_project', engine, if_exists='replace', index=False)
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'
[2024-12-04T15:47:52.812+0100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=data_warehouse_etl, task_id=load_dimensions, run_id=manual__2024-12-04T14:42:16.988033+00:00, execution_date=20241204T144216, start_date=20241204T144752, end_date=20241204T144752
[2024-12-04T15:47:52.816+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-04T15:47:52.816+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 23 for task load_dimensions ('Engine' object has no attribute 'cursor'; 46326)
Traceback (most recent call last):
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/dags/dim_process.py", line 86, in load_dimensions
    projects.to_sql('dim_project', engine, if_exists='replace', index=False)
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/core/generic.py", line 3087, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2850, in to_sql
    table.create()
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 984, in create
    if self.exists():
       ^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 970, in exists
    return self.pd_sql.has_table(self.name, self.schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2865, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sijibomijoshua/airflow/airflow_env/lib/python3.11/site-packages/pandas/io/sql.py", line 2672, in execute
    cur = self.con.cursor()
          ^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'cursor'
[2024-12-04T15:47:52.849+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-04T15:47:52.855+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-04T15:47:52.856+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
